name: Retain
options:
  bundleIdPrefix: com.empatika
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.4"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "0.1.7-beta"
    CURRENT_PROJECT_VERSION: "4"
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "6.24.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.6.0"

targets:
  Retain:
    type: application
    platform: macOS
    sources:
      - path: Sources/Retain
        excludes:
          - "**/*.md"
      - path: Resources/AppIcon.icns
        buildPhase: resources
    dependencies:
      - package: GRDB
      - package: Sparkle
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.empatika.Retain
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: Retain
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        ENABLE_APP_SANDBOX: NO
    entitlements:
      path: Resources/Retain.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.files.user-selected.read-write: true
    info:
      path: Resources/Info.plist
      properties:
        CFBundleIconFile: AppIcon
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSApplicationCategoryType: public.app-category.developer-tools
        NSHighResolutionCapable: true
        NSSupportsAutomaticTermination: true
        NSSupportsSuddenTermination: true
        LSUIElement: false
        CFBundleURLTypes:
          - CFBundleURLName: com.empatika.Retain
            CFBundleURLSchemes:
              - retain
        SUFeedURL: https://raw.githubusercontent.com/BayramAnnakov/retain/main/appcast.xml
        SUPublicEDKey: 0oUDQBQMD7S9b04m7u/UmG6ee9KX9IfgtVCbOsgMK+M=
        SUEnableAutomaticChecks: true
        SUAllowsAutomaticUpdates: true
        NSUserActivityTypes:
          - com.apple.corespotlightitem
