name: Retain
options:
  bundleIdPrefix: com.empatika
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: "6.24.0"

targets:
  Retain:
    type: application
    platform: macOS
    sources:
      - path: Sources/Retain
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.empatika.Retain
        PRODUCT_NAME: Retain
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Retain
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright 2024-2026"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: NO
    entitlements:
      path: Retain.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
    scheme:
      testTargets:
        - RetainUITests
      gatherCoverageData: true
      testPlans:
        - path: Retain.xctestplan
          defaultPlan: true

  RetainUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: Tests/RetainUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Retain
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.empatika.Retain.uitests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        TEST_TARGET_NAME: Retain
        INFOPLIST_FILE: Tests/RetainUITests/Info.plist
        DEAD_CODE_STRIPPING: NO
        OTHER_LDFLAGS: "-ObjC -all_load"
